version: '3.8'

networks:
  betting-net:
    driver: bridge

services:
  kafka:
    image: confluentinc/cp-kafka:7.7.7
    container_name: betting_kafka
    networks:
      - betting-net
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@betting_kafka:29093'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_LISTENERS: 'PLAINTEXT://betting_kafka:29092,CONTROLLER://betting_kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://betting_kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: betting_kafka_ui
    networks:
      - betting-net
    depends_on:
      - kafka
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: betting_kafka:29092

  rocketmq-nameserver:
    image: apache/rocketmq:4.9.7
    container_name: betting_rmq_namesrv
    networks:
      - betting-net
    ports:
      - "9876:9876"
    environment:
      - JAVA_OPT_EXT=-Xms256m -Xmx256m
    command: sh mqnamesrv
    extra_hosts:
      - "host.docker.internal:host-gateway"

  rocketmq-broker:
    image: apache/rocketmq:4.9.7
    container_name: betting_rmq_broker
    networks:
      - betting-net
    ports:
      - "10909:10909"
      - "10911:10911"
    environment:
      - NAMESRV_ADDR=rocketmq-nameserver:9876
      - JAVA_OPT_EXT=-Xms512m -Xmx512m
    depends_on:
      - rocketmq-nameserver
    volumes:
      - ./rocketmq/broker.conf:/home/rocketmq/rocketmq-4.9.7/conf/broker.conf
    command: sh mqbroker -n rocketmq-nameserver:9876 -c /home/rocketmq/rocketmq-4.9.7/conf/broker.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"

  rocketmq-dashboard:
    image: styletang/rocketmq-console-ng:1.0.0
    container_name: betting_rmq_dashboard
    networks:
      - betting-net
    depends_on:
      - rocketmq-nameserver
    ports:
      - "8082:8080"
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=rocketmq-nameserver:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false
    extra_hosts:
      - "host.docker.internal:host-gateway"
