server:
  port: 8080

spring:
  application:
    name: hexagonal-betting-engine

  datasource:
    url: jdbc:h2:mem:bettingdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true
        linger.ms: 5
        delivery.timeout.ms: 60000
        retries: 2147483647
        retry.backoff.ms: 500
    consumer:
      group-id: hexagonal-betting-engine
      enable-auto-commit: false
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      auto-offset-reset: earliest
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.mario.hexagonalbettingengine.infrastructure.*"
        isolation.level: read_committed

rocketmq:
  name-server: localhost:9876
  producer:
    group: ${app.messaging.rocketmq.producer-group}
    send-message-timeout: 30000

app:
  messaging:
    rocketmq:
      enabled: false
      topic: bet-settlements
      producer-group: hexagonal-betting-engine
    kafka:
      event-outcomes:
        topic: event-outcomes
        dlq-topic: event-outcomes-dlq
        partitions: 3
        replicas: 1
        dlq-partitions: 1
        dlq-replicas: 1
        retry-interval: 1000
        retry-attempts: 3
        concurrency: 3
